name: fokuskripto
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.1.0
  crypto: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  provider: ^6.1.5
  dropdown_search: ^5.0.6
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.7 
  path_provider: ^2.1.3
  geolocator: ^11.0.0 
  geocoding: ^3.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0 
  build_runner: ^2.3.0   

flutter:
  uses-material-design: true
